const state={cases:[],selected:null,timeline:[]};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const key=prefix=>`${prefix}-${crypto.randomUUID()}`;

async function api(path,options={}){
  const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});
  const payload=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(`${payload.message||'请求失败'}${payload.field?`（${payload.field}）`:''}`);
  return payload.data;
}
function notice(message,error=false){const box=$('#notice');box.textContent=message;box.classList.toggle('error',error);box.hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>box.hidden=true,5000)}
function body(meta={}){return{expectedVersion:state.selected.version,idempotencyKey:key('web'),actor:'操作员-01',...meta}}

async function refreshCases(selectId){
  state.cases=await api('/api/cases?limit=100');$('#caseCount').textContent=state.cases.length;renderCaseList();
  const target=selectId||state.selected?.id;if(target)await selectCase(target);
}
function renderCaseList(){const host=$('#caseList');if(!state.cases.length){host.innerHTML='<p class="empty">尚无批次</p>';return}host.innerHTML=state.cases.map(item=>`<button class="case-card ${state.selected?.id===item.id?'active':''}" data-id="${esc(item.id)}"><strong>${esc(item.accessionCode)}</strong><small>${esc(item.status)} · v${item.version}</small></button>`).join('');host.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>selectCase(button.dataset.id)))}
async function selectCase(id){const workbench=await api(`/api/cases/${encodeURIComponent(id)}`);state.selected=workbench.case;state.timeline=workbench.timeline;$('#noSelection').hidden=true;$('#caseWorkspace').hidden=false;renderCase();renderCaseList()}
function renderCase(){const c=state.selected;if(!c)return;$('#caseCode').textContent=c.accessionCode;$('#caseTitle').textContent=c.source;$('#caseMeta').textContent=`收获 ${c.harvestedAt} · 声明 ${c.declaredSeedCount} 粒 · ${c.protocolCode}`;$('#caseStatus').textContent=statusName(c.status);$('#caseVersion').textContent=`版本 v${c.version}`;renderSampling(c.samplingPlan);const observations=[...(c.observations||[]),...(c.supplementalTrials||[]).flatMap(t=>t.observations||[])];renderObservations(observations);renderMetrics(c.analysis);renderDeviations(c.deviations||[]);renderTimeline();setAvailability(c.status);if(c.credential){$('#verifyForm [name=credentialNo]').value=c.credential.credentialNo}}
function statusName(status){return({draft:'待抽样',sampling_confirmed:'抽样已确认',observing:'观测/偏差处置',pending_review:'待复核',returned:'已退回',approved:'已批准',frozen:'证据已冻结',credential_issued:'凭据已签发'})[status]||status}
function setAvailability(status){$('#samplingForm button').disabled=status!=='draft';$('#observationForm button').disabled=!['sampling_confirmed','observing','returned','pending_review'].includes(status);$('#analyzeButton').disabled=!['observing','returned'].includes(status);$('#reviewForm button').disabled=status!=='pending_review';$('#freezeButton').disabled=status!=='approved';$('#issueButton').disabled=status!=='frozen'}
function renderSampling(plan){const host=$('#samplingSummary');if(!plan){host.innerHTML='';return}host.innerHTML=`<p>已抽样 <strong>${plan.totalSampled}</strong> 粒（${plan.samplingRatio}%），剩余留样 <strong>${plan.remainingReserve}</strong> 粒</p><table><thead><tr><th>样品单元</th><th>配额</th><th>重复组</th></tr></thead><tbody>${(plan.unitQuotas||[]).map(q=>`<tr><td>${esc(q.unitName)}</td><td>${q.plannedCount}</td><td>${q.replicateNos.join('、')}</td></tr>`).join('')}</tbody></table>`}
function renderObservations(items){const host=$('#observationMatrix');if(!items.length){host.innerHTML='<p class="empty">尚无观测修订</p>';return}host.innerHTML=`<table><thead><tr><th>试验</th><th>重复组</th><th>日</th><th>修订</th><th>正常</th><th>异常</th><th>未发芽</th><th>污染</th><th>温度</th><th>状态</th></tr></thead><tbody>${items.map(o=>`<tr><td>${esc(o.supplementalTrialId||'原试验')}</td><td>${o.replicateNo}</td><td>${o.dayNo}</td><td>r${o.revision}</td><td>${o.normalCount}</td><td>${o.abnormalCount}</td><td>${o.ungerminatedCount}</td><td>${o.contaminatedCount}</td><td>${o.temperatureC}℃</td><td>${o.submitted?'已提交':'草稿'}</td></tr>`).join('')}</tbody></table>`}
function renderMetrics(analysis){const host=$('#metrics');if(!analysis){host.innerHTML='';return}const m=analysis.metric;const trajectory=(analysis.trajectories||[]).map(p=>`组${p.replicateNo}·第${p.dayNo}日 ${p.germinationRate}%（Δ${p.adjacentDayDelta}）`).join('；');host.innerHTML=`<div class="metric"><strong>${m.germinationRate}%</strong>发芽率</div><div class="metric"><strong>${m.effectiveSampleSize}</strong>有效样本</div><div class="metric"><strong>${m.replicateDifference}</strong>组间差</div><div class="metric"><strong>${esc(m.candidateDecision)}</strong>候选结论</div>${trajectory?`<p class="wide">逐日轨迹：${esc(trajectory)}</p>`:''}`}
function renderDeviations(items){const active=items.filter(item=>item.status==='open'||item.status==='in_progress');const host=$('#deviationList');if(!active.length){host.innerHTML='<p class="empty">无待处置偏差</p>';return}host.innerHTML=active.map(d=>`<article class="deviation" data-id="${esc(d.id)}"><code>${esc(d.ruleCode)}</code> <span>${esc(d.severity)} · ${esc(d.status)}</span><p>证据：${d.evidenceRefs.map(esc).join('、')}</p>${d.status==='in_progress'?`<p>补充试验：<strong>${esc(d.supplementalTrialId)}</strong>，请在观测矩阵切换该 ID 后录入并分析。</p>`:`<form><input name="cause" placeholder="原因说明" required><input name="correctiveAction" placeholder="纠正措施" required><label class="check"><input name="startSupplementalTrial" type="checkbox" ${d.severity==='critical'?'checked':''}> 由系统发起补充试验</label><input name="actor" value="试验员-01" required><button class="accent" type="submit">提交处置</button></form>`}</article>`).join('');host.querySelectorAll('form').forEach(form=>form.addEventListener('submit',resolveDeviation))}
function renderTimeline(){const host=$('#timeline');host.innerHTML=state.timeline.map(e=>`<li><strong>#${e.sequence}</strong><span>${esc(e.action)} · ${esc(e.actor)}</span><time>${new Date(e.occurredAt).toLocaleString('zh-CN')}</time></li>`).join('')||'<li>暂无审计事件</li>'}

$('#createForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{const created=await api('/api/cases',{method:'POST',body:JSON.stringify({idempotencyKey:key('create'),actor:f.get('actor'),accessionCode:f.get('accessionCode'),source:f.get('source'),harvestedAt:f.get('harvestedAt'),declaredSeedCount:Number(f.get('declaredSeedCount')),protocolCode:f.get('protocolCode')})});notice('批次建档成功');await refreshCases(created.id)}catch(error){notice(error.message,true)}});
$('#samplingForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{const unitQuotas=f.get('unitQuotas').split(/\n/).filter(Boolean).map(line=>{const [unitName,plannedCount,groups]=line.split(',');return{unitName:unitName.trim(),plannedCount:Number(plannedCount),replicateNos:groups.split(/[+、]/).map(Number)}});state.selected=await api(`/api/cases/${state.selected.id}/sampling-plan/confirm`,{method:'POST',body:JSON.stringify(body({actor:f.get('actor'),unitQuotas,replicateCount:Number(f.get('replicateCount')),seedsPerReplicate:Number(f.get('seedsPerReplicate')),temperatureMinC:Number(f.get('temperatureMinC')),temperatureMaxC:Number(f.get('temperatureMaxC')),environmentNotes:f.get('environmentNotes')}))});notice('抽样方案已确认并固定配额');await selectCase(state.selected.id)}catch(error){notice(error.message,true)}});
$('#observationForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{const submitted=f.get('submitted')==='on';const supplementalTrialId=f.get('supplementalTrialId').trim();const rows=f.get('matrixRows').split(/\n/).filter(Boolean).map(line=>{const values=line.split(',').map(Number);return{replicateNo:values[0],dayNo:values[1],normalCount:values[2],abnormalCount:values[3],ungerminatedCount:values[4],contaminatedCount:values[5],temperatureC:values[6],submitted,supplementalTrialId}});const result=await api(`/api/cases/${state.selected.id}/observations`,{method:'POST',body:JSON.stringify(body({actor:f.get('actor'),supplementalTrialId,rows}))});notice(`已原子保存 ${result.acceptedRows} 行：草稿 ${result.draftCount}，正式 ${result.submittedCount}`);await selectCase(state.selected.id)}catch(error){notice(error.message,true)}});
$('#analyzeButton').addEventListener('click',async()=>{try{const supplementalTrialId=$('#observationForm [name=supplementalTrialId]').value.trim();state.selected=await api(`/api/cases/${state.selected.id}/analysis`,{method:'POST',body:JSON.stringify(body({actor:'试验员-01',supplementalTrialId}))});notice(supplementalTrialId?'补充试验独立分析完成':(state.selected.analysis.findings.length?'分析完成，请处置偏差':'分析通过，已进入待复核'));await selectCase(state.selected.id)}catch(error){notice(error.message,true)}});
async function resolveDeviation(event){event.preventDefault();const article=event.currentTarget.closest('article');const f=new FormData(event.currentTarget);try{state.selected=await api(`/api/cases/${state.selected.id}/deviations/${article.dataset.id}/resolve`,{method:'POST',body:JSON.stringify(body({actor:f.get('actor'),cause:f.get('cause'),correctiveAction:f.get('correctiveAction'),startSupplementalTrial:f.get('startSupplementalTrial')==='on'}))});notice('偏差处置已记录；系统已按选择创建补充试验');await selectCase(state.selected.id)}catch(error){notice(error.message,true)}}
$('#reviewForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{state.selected=await api(`/api/cases/${state.selected.id}/review`,{method:'POST',body:JSON.stringify(body({actor:f.get('actor'),decision:f.get('decision'),reason:f.get('reason')}))});notice(f.get('decision')==='approve'?'鉴定结论已批准':'已退回观测整改');await selectCase(state.selected.id)}catch(error){notice(error.message,true)}});
$('#freezeButton').addEventListener('click',async()=>{try{state.selected=await api(`/api/cases/${state.selected.id}/freeze`,{method:'POST',body:JSON.stringify(body({actor:'复核员-01'}))});notice(`证据已冻结：${state.selected.evidenceBundle.digest.slice(0,16)}…`);await selectCase(state.selected.id)}catch(error){notice(error.message,true)}});
$('#issueButton').addEventListener('click',async()=>{try{const credential=await api(`/api/cases/${state.selected.id}/credential`,{method:'POST',body:JSON.stringify(body({actor:'复核员-01'}))});notice(`凭据已签发：${credential.credentialNo}`);$('#verifyForm [name=credentialNo]').value=credential.credentialNo;await selectCase(state.selected.id)}catch(error){notice(error.message,true)}});
$('#verifyForm').addEventListener('submit',async event=>{event.preventDefault();const number=new FormData(event.currentTarget).get('credentialNo');try{const result=await api(`/api/credentials/${encodeURIComponent(number)}/verify`);$('#verifyResult').innerHTML=`<div class="${result.valid?'valid':'deviation'}"><strong>${esc(result.message)}</strong><p>存储摘要：<code>${esc(result.storedDigest)}</code></p><p>重算摘要：<code>${esc(result.recalculatedDigest)}</code></p><ul>${result.checks.map(check=>`<li>${check.passed?'✓':'✗'} ${esc(check.code)}：${esc(check.message)}</li>`).join('')}</ul><p>审计事件：${result.timeline.length} 条 · 冻结包 ${esc(result.credential.evidenceBundleId)}</p></div>`}catch(error){notice(error.message,true)}});
$('#refreshCases').addEventListener('click',()=>refreshCases().catch(error=>notice(error.message,true)));
document.querySelector('#createForm [name=harvestedAt]').value=new Date(Date.now()-86400000).toISOString().slice(0,10);
refreshCases().catch(error=>notice(error.message,true));
